update: get license from Bintray and Bintray creds from 1password

diff --git a/license b/license
--- a/license
+++ b/license
@@ -11,13 +11,22 @@ FILE=license.json
 OP_ACCOUNT=team_kong
 
 # License entry uuid, use `op list items | jq` to find the right uuid.
-OP_UUID=cce3ryazn5aczhgmfdvcdaryaq
-
-
+OP_UUID=dkuc26kncfeepcrnr32aybvguy
 
 
 # Nothing to customize below
 FILENAME="$LOCATION/$FILE"
+
+
+function cleanup_kong_license_vars {
+  unset LOCATION FILE OP_ACCOUNT FILENAME
+  unset PRODUCT COMPANY EXPIRE
+  unset EXPIRE_EPOCH NOW_EPOCH WARN_EPOCH EXPIRE_IN
+  unset OP_TOKEN OP_UUID DETAILS
+  unset BINTRAY_APIKEY BINTRAY_USERNAME BINTRAY_REPO
+  unset NEW_KEY OLD_SIG NEW_SIG
+}
+
 
 if [ "$1" == "--help" ]; then
   echo "Utility to automatically set the Kong Enterprise license"
@@ -34,6 +43,7 @@ if [ "$1" == "--help" ]; then
   echo "For convenience you can add the following to your bash profile:"
   echo "    source $BASH_SOURCE --no-update"
   echo
+  cleanup_kong_license_vars
   [[ $0 != $BASH_SOURCE ]] && return 0 || exit 0
 fi
 
@@ -42,6 +52,7 @@ if [ "$1" == "--clean" ]; then
   rm "$FILENAME"  > /dev/null 2>&1
   rmdir "$LOCATION"  > /dev/null 2>&1
   echo "Removed cached files"
+  cleanup_kong_license_vars
   [[ $0 != $BASH_SOURCE ]] && return 0 || exit 0
 fi
 
@@ -55,6 +66,7 @@ if [ $? -ne 0 ]; then
   echo
   echo "Use --help for info."
   echo
+  cleanup_kong_license_vars
   [[ $0 != $BASH_SOURCE ]] && return 0 || exit 0
 fi
 
@@ -65,6 +77,7 @@ if [ $? -ne 0 ]; then
   echo
   echo "See: https://stedolan.github.io/jq/"
   echo
+  cleanup_kong_license_vars
   [[ $0 != $BASH_SOURCE ]] && return 0 || exit 0
 fi
 
@@ -147,6 +160,7 @@ if (( $NOW_EPOCH < $EXPIRE_EPOCH )); then
   # check if we're forcing an update, despite being valid
   if [ ! "$1" == "--update" ]; then
     # all is well, we're done
+    cleanup_kong_license_vars
     [[ $0 != $BASH_SOURCE ]] && return 0 || exit 0
   fi
 
@@ -159,41 +173,62 @@ else
     echo
     echo "run the following command to initiate an update:"
     echo "    source $BASH_SOURCE"
+    cleanup_kong_license_vars
     [[ $0 != $BASH_SOURCE ]] && return 0 || exit 0
   fi
 fi
 
 
-
 # sign in to 1Password
 echo
-TOKEN_CMD=$(op signin $OP_ACCOUNT)
+echo "Logging into 1Password..."
+OP_TOKEN=$(op signin $OP_ACCOUNT --output=raw)
 if [ ! $? == 0 ]; then
   # an error while logging into 1Password
   echo [ERROR] Failed to get a 1Password token, license data not updated.
+  cleanup_kong_license_vars
   [[ $0 != $BASH_SOURCE ]] && return 1 || exit 1
 fi
 
 
-# Go and fetch the license key
-eval $TOKEN_CMD
-NEW_KEY=$(op get item $OP_UUID | jq '.details.sections[].fields[]? | select(.t=="license key").v | fromjson')
+# Get the Bintray credentials
+DETAILS=$(op get item $OP_UUID --session=$OP_TOKEN)
 if [ ! $? == 0 ]; then
-  # an error while fetching the new license key
-  echo [ERROR] Failed to get the new license from 1Password, license data not updated.
+  # an error while fetching the Bintray keys
+  echo [ERROR] Failed to get the data from 1Password, license data not updated.
+  # sign out again
+  op signout --session=$OP_TOKEN
+  cleanup_kong_license_vars
   [[ $0 != $BASH_SOURCE ]] && return 1 || exit 1
 fi
 
 
 # sign out again
-op signout
+op signout --session=$OP_TOKEN
+
+
+BINTRAY_APIKEY=$(echo $DETAILS | jq '.details.fields[]? | select(.designation=="password").value' | sed s/\"//g)
+BINTRAY_USERNAME=$(echo $DETAILS | jq '.details.fields[]? | select(.designation=="username").value' | sed s/\"//g)
+BINTRAY_REPO=$(echo $DETAILS | jq '.details.sections[].fields[]? | select(.t=="Package/Repository").v' | sed s/\"//g)
+
+
+echo "Downloading license..."
+NEW_KEY=$(curl -s -L -u"$BINTRAY_USERNAME:$BINTRAY_APIKEY" "https://kong.bintray.com/$BINTRAY_REPO/license.json")
+if [[ ! $NEW_KEY == *"signature"* || ! $NEW_KEY == *"payload"* ]]; then
+  echo "[ERROR] failed to download the Kong Enterprise license file
+    $NEW_KEY"
+  cleanup_kong_license_vars
+  [[ $0 != $BASH_SOURCE ]] && return 1 || exit 1
+fi
+
 
 # validate it is different
 OLD_SIG=$(echo $KONG_LICENSE_DATA | jq '.license.signature' | sed s/\"//g)
 NEW_SIG=$(echo $NEW_KEY | jq '.license.signature' | sed s/\"//g)
 
 if [ "$OLD_SIG" == "$NEW_SIG" ]; then
-  echo [ERROR] The new license is the same as the old one, seems 1Password was not updated yet.
+  echo [ERROR] The new license is the same as the old one, seems the Bintray license was not updated yet.
+  cleanup_kong_license_vars
   [[ $0 != $BASH_SOURCE ]] && return 1 || exit 1
 fi
 
@@ -206,4 +241,4 @@ PRODUCT=$(echo $KONG_LICENSE_DATA | jq '.license.payload.product_subscription' |
 COMPANY=$(echo $KONG_LICENSE_DATA | jq '.license.payload.customer' | sed s/\"//g)
 EXPIRE=$(echo $KONG_LICENSE_DATA | jq '.license.payload.license_expiration_date' | sed s/\"//g)
 echo $PRODUCT licensed to $COMPANY, license expires: $EXPIRE
-
+cleanup_kong_license_vars
